// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'arrow': string;
  'icon': string;
  'item': string;
  'item_subtitle': string;
  'item_title': string;
  'items': string;
  'main': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
