// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'button': string;
  'close': string;
  'content': string;
  'free_trial': string;
  'main': string;
  'price': string;
  'subtitle': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
