// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'date': string;
  'left': string;
  'main': string;
  'month': string;
  'right': string;
  'year': string;
}
export const cssExports: CssExports;
export default cssExports;
