export type FinancialStatus = 'bad' | 'ok' | 'good' | 'great'
export type SpendingOn = 'myself' | 'partner' | 'child' | 'pet' | 'teenager' | 'parents'
export type LivingPlace = 'rent' | 'personal dwelling' | 'mortgage'
export type HasDebt = 'credit' | 'credit card' | 'microloan' | 'personal debt' | 'installment'
export type Transportation = 'car' | 'public transportation' | 'taxi' | 'walk' | 'motorcycle' | 'bicycle'
export type RegularExpense =
    | 'internet'
    | 'cellular network'
    | 'self care'
    | 'clothes'
    | 'medicine'
    | 'smoking'
    | 'fitness'
    | 'swimming pool'
    | 'groceries'
export type Subscription =
    | 'yandex plus'
    | 'tinkoff pro'
    | 'sbep prime'
    | 'telegram premium'
    | 'ozon premium'
    | 'litres'
    | 'vk music'
export type Goal =
    | 'rainy day'
    | 'retirement'
    | 'investments'
    | 'real estate'
    | 'car'
    | 'travel'
    | 'wedding'
    | 'nothing matches'
export type Additional = 'entertainment' | 'restaurants' | 'charity' | 'presents' | 'games' | 'delivery' | 'fast food'
