// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'container': string;
  'credit_card': string;
  'main': string;
  'money_chart': string;
  'text_box': string;
  'text_five': string;
  'text_four': string;
  'text_one': string;
  'text_seven': string;
  'text_six': string;
  'text_three': string;
  'text_two': string;
}
export const cssExports: CssExports;
export default cssExports;
