// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'acc_diff': string;
  'acc_diff_budget': string;
  'content': string;
  'date': string;
  'header': string;
  'header_title': string;
  'more': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
