// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'btn': string;
  'close': string;
  'go_back': string;
  'main': string;
  'subtitle': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
