// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'buttons': string;
  'delete_account': string;
  'external_accounts': string;
  'info': string;
  'log_out_btn': string;
  'profile_account': string;
}
export const cssExports: CssExports;
export default cssExports;
