// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'delete_account': string;
  'log_out_btn': string;
}
export const cssExports: CssExports;
export default cssExports;
