// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'btn': string;
  'cancel': string;
  'delete': string;
  'header': string;
  'header_actions': string;
  'input': string;
  'input_block': string;
  'label': string;
  'main': string;
  'make_goal': string;
  'ruble': string;
  'ruble_block': string;
}
export const cssExports: CssExports;
export default cssExports;
