// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'arrow': string;
  'arrow_down': string;
  'arrows': string;
  'buttons': string;
  'close': string;
  'main': string;
  'months': string;
  'ok': string;
  'year': string;
}
export const cssExports: CssExports;
export default cssExports;
