// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actions': string;
  'btn': string;
  'cancel': string;
  'content': string;
  'date_block': string;
  'delete': string;
  'header': string;
  'input_block': string;
  'label': string;
  'main': string;
  'ruble': string;
  'ruble_block': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
