// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'check_block': string;
  'close': string;
  'coin1': string;
  'coin2': string;
  'coin3': string;
  'content': string;
  'free': string;
  'free_btn': string;
  'free_content': string;
  'free_content_item': string;
  'free_duration': string;
  'free_price': string;
  'free_title': string;
  'main': string;
  'plus': string;
  'plus_btn': string;
  'plus_content': string;
  'plus_content_item': string;
  'plus_duration': string;
  'plus_price': string;
  'plus_title': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
