// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'container': string;
  'email': string;
  'email_block': string;
  'enter': string;
  'enter_block': string;
  'enter_button': string;
  'enter_with_block': string;
  'forgot_password': string;
  'inputs': string;
  'logo': string;
  'main': string;
  'password': string;
  'password_block': string;
  'socials': string;
  'tabs': string;
}
export const cssExports: CssExports;
export default cssExports;
