// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'answer': string;
  'answer_input': string;
  'main': string;
  'reset_input': string;
}
export const cssExports: CssExports;
export default cssExports;
