// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'go_to_main': string;
  'header': string;
  'main': string;
  'text': string;
}
export const cssExports: CssExports;
export default cssExports;
