// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'btn': string;
  'cancel': string;
  'header': string;
  'icon': string;
  'input_block': string;
  'main': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
