// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'input': string;
  'input_block': string;
  'label': string;
  'ruble': string;
  'ruble_block': string;
}
export const cssExports: CssExports;
export default cssExports;
