// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'cancel': string;
  'content': string;
  'create_account': string;
  'create_account_main': string;
  'header': string;
  'hint': string;
  'input': string;
  'input_block': string;
  'item': string;
  'label': string;
  'main': string;
  'more': string;
  'name': string;
  'question': string;
  'ruble': string;
  'ruble_block': string;
  'save_btn': string;
  'sum': string;
  'sum_block': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
