// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'close': string;
  'content': string;
  'date': string;
  'input': string;
  'input_block': string;
  'label': string;
  'main': string;
  'pay_btn': string;
  'price': string;
  'subtitle': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
