// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'btn': string;
  'buttons': string;
  'card': string;
  'card_icon': string;
  'card_name': string;
  'card_number': string;
  'change_button': string;
  'chart': string;
  'coin1': string;
  'coin2': string;
  'coin3': string;
  'connected_header': string;
  'connected_main': string;
  'content': string;
  'disconnect': string;
  'gear': string;
  'header': string;
  'images': string;
  'main': string;
  'next_write_off': string;
  'status': string;
  'subscription': string;
  'subtitle': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
