// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'icon': string;
  'item': string;
  'item_text': string;
  'item_text_delete': string;
  'main': string;
}
export const cssExports: CssExports;
export default cssExports;
