// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'button_back': string;
  'button_next': string;
  'button_skip': string;
  'nav_buttons': string;
  'page_number': string;
  'progress': string;
  'progress_bar': string;
  'progress_bar__empty': string;
  'progress_bar__fill': string;
  'question': string;
}
export const cssExports: CssExports;
export default cssExports;
