// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'code_input': string;
  'code_input__block': string;
  'code_input_clear': string;
  'confirm': string;
  'go_back': string;
  'header': string;
  'main': string;
  'resend_code': string;
  'text': string;
}
export const cssExports: CssExports;
export default cssExports;
