// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'check_mark': string;
  'edit': string;
  'icon': string;
  'id': string;
  'info': string;
  'input': string;
  'main': string;
  'name__block': string;
  'name__text': string;
  'name_edit_block': string;
  'plus': string;
}
export const cssExports: CssExports;
export default cssExports;
