// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'icon': string;
  'more': string;
  'section': string;
  'section_add_new_element': string;
  'section_header': string;
  'section_header_price': string;
  'section_header_title': string;
  'section_item': string;
  'section_item_block': string;
  'section_item_price_block': string;
  'setting': string;
  'setting_delete': string;
  'settings': string;
}
export const cssExports: CssExports;
export default cssExports;
