// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'buttons': string;
  'main': string;
  'no': string;
  'title': string;
  'yes': string;
}
export const cssExports: CssExports;
export default cssExports;
