// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'cancel': string;
  'main': string;
  'plus': string;
  'price': string;
  'subtitle': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
