// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'date': string;
  'items': string;
  'more': string;
  'sum_block': string;
}
export const cssExports: CssExports;
export default cssExports;
