// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'buttons': string;
  'cancel': string;
  'confirm': string;
  'input_block': string;
  'main': string;
}
export const cssExports: CssExports;
export default cssExports;
