// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'balance': string;
  'buttons': string;
  'current_budget': string;
  'current_budget_content': string;
  'current_budget_header': string;
  'date': string;
  'expenses': string;
  'expenses_content': string;
  'expenses_header': string;
  'main': string;
  'refill': string;
  'title': string;
  'write_off': string;
}
export const cssExports: CssExports;
export default cssExports;
