// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'analytics': string;
  'arrow': string;
  'expand': string;
  'expand_block': string;
  'item': string;
  'main': string;
  'open_content': string;
  'open_header': string;
  'open_main': string;
  'progress_bar': string;
  'progress_bar_block': string;
  'progress_bar_subtitle': string;
  'progress_bar_title': string;
  'subtitle': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
