// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'content_item': string;
  'content_item_text': string;
  'delete_buttons': string;
  'delete_main': string;
  'delete_no': string;
  'delete_title': string;
  'delete_yes': string;
  'icon': string;
  'main': string;
}
export const cssExports: CssExports;
export default cssExports;
