// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'content_header': string;
  'content_items': string;
  'header': string;
  'header_price': string;
  'main': string;
}
export const cssExports: CssExports;
export default cssExports;
