// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'cancel': string;
  'check': string;
  'content_header': string;
  'content_items': string;
  'edit_name_header': string;
  'group_item_create': string;
  'header': string;
  'header_block': string;
  'header_block_title': string;
  'header_price': string;
  'header_title_text': string;
  'icon': string;
  'input': string;
  'main': string;
  'more': string;
}
export const cssExports: CssExports;
export default cssExports;
