// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'container': string;
  'email': string;
  'email_block': string;
  'enter': string;
  'enter_block': string;
  'enter_block_active': string;
  'enter_with__block': string;
  'input_clear': string;
  'input_error': string;
  'inputs': string;
  'logo': string;
  'main': string;
  'password': string;
  'password_block': string;
  'registration': string;
  'social': string;
  'socials': string;
  'tabs': string;
}
export const cssExports: CssExports;
export default cssExports;
