// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'details': string;
  'free_plan': string;
  'glass_chart': string;
  'glass_pipe': string;
  'main': string;
  'price': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
