// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'change_password': string;
  'check_block': string;
  'edit': string;
  'edit_block': string;
  'input': string;
  'item': string;
  'items': string;
  'main': string;
  'title': string;
  'value': string;
}
export const cssExports: CssExports;
export default cssExports;
