// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'header': string;
  'header_price': string;
  'header_subtitle': string;
  'header_title': string;
  'header_title_date': string;
  'main': string;
}
export const cssExports: CssExports;
export default cssExports;
