// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'checkMark': string;
  'confirm': string;
  'eye': string;
  'form': string;
  'form_item': string;
  'header': string;
  'input': string;
  'input__block': string;
  'input_label': string;
  'main': string;
  'text': string;
  'text__block': string;
}
export const cssExports: CssExports;
export default cssExports;
