// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'archive': string;
  'archive_content': string;
  'archive_header': string;
  'archive_main': string;
  'buttons': string;
  'cancel': string;
  'close': string;
  'close_active': string;
  'content': string;
  'delete_modal': string;
  'goal': string;
  'header': string;
  'hint': string;
  'item': string;
  'items': string;
  'main': string;
  'name': string;
  'no': string;
  'plan': string;
  'question': string;
  'saved': string;
  'saving': string;
  'sum': string;
  'title': string;
  'yes': string;
}
export const cssExports: CssExports;
export default cssExports;
