// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'add_circle': string;
  'content': string;
  'header': string;
  'income': string;
  'income_content': string;
  'income_content_header': string;
  'income_content_header_items': string;
  'income_header': string;
  'income_header_month': string;
  'income_header_subtitle': string;
  'income_header_title': string;
  'income_header_year': string;
  'main': string;
  'round_border': string;
  'round_border_default': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
